# Install ROS CI Action to build ROS workspace
name: ROS 2 CI Action
# uses: ros-tooling/action-ros-ci@0.2.6

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Sets up ROS worker and installs system dependencies
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: noetic
      - run: "source /opt/ros/noetic/setup.bash && rosnode --help"

      # Builds ROS 1 workspace
      - name: Build ROS Workspace
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: runt_rover
          target-ros1-distro: noetic
          skip-tests: true